version: '3.8'
services:
  back:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - MONGO_URI=mongodb://mongo:27017/back
    depends_on:
      - mongo
  mongo:
    image: mongo:4
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  front:
    build: ./front
    ports:
      - "80:80"
    depends_on:
      - api

volumes:
  mongodb_data:
